/**
 * UCP Logs Module
 * Admin module for viewing checkout sessions and webhook deliveries
 */

import './page/ucp-logs-sessions';
import './page/ucp-logs-webhooks';

const { Module } = Shopware;

Module.register('ucp-logs', {
    type: 'plugin',
    name: 'ucp-logs',
    title: 'ucp-logs.general.title',
    description: 'ucp-logs.general.description',
    color: '#ff6b35',
    icon: 'regular-file-text',
    favicon: 'icon-module-settings.png',

    snippets: {
        'en-GB': {
            'ucp-logs': {
                general: {
                    title: 'UCP Logs',
                    description: 'View checkout sessions and webhook deliveries',
                },
                navigation: {
                    sessions: 'Checkout Sessions',
                    webhooks: 'Webhook Deliveries',
                },
                sessions: {
                    title: 'Checkout Sessions',
                    description: 'View and debug checkout session history',
                    columnSession: 'Session ID',
                    columnShop: 'Shop',
                    columnStatus: 'Status',
                    columnPlatform: 'Platform',
                    columnOrder: 'Order',
                    columnCreated: 'Created',
                    columnExpires: 'Expires',
                    filterStatus: 'Status',
                    filterAll: 'All',
                    statusIncomplete: 'Incomplete',
                    statusComplete: 'Complete',
                    statusFailed: 'Failed',
                    statusExpired: 'Expired',
                    detailTitle: 'Session Details',
                    detailGeneral: 'General',
                    detailCart: 'Cart Data',
                    detailPayment: 'Payment',
                    detailAddresses: 'Addresses',
                    noData: 'No checkout sessions found',
                },
                webhooks: {
                    title: 'Webhook Deliveries',
                    description: 'Monitor webhook delivery status',
                    columnEvent: 'Event',
                    columnTarget: 'Target URL',
                    columnStatus: 'Status',
                    columnAttempts: 'Attempts',
                    columnLastError: 'Last Error',
                    columnCreated: 'Created',
                    columnDelivered: 'Delivered',
                    filterStatus: 'Status',
                    filterAll: 'All',
                    statusPending: 'Pending',
                    statusSent: 'Sent',
                    statusFailed: 'Failed',
                    statusRetrying: 'Retrying',
                    retryButton: 'Retry',
                    retrySuccess: 'Webhook retry initiated',
                    retryFailed: 'Failed to retry webhook',
                    noData: 'No webhook deliveries found',
                },
            },
        },
        'de-DE': {
            'ucp-logs': {
                general: {
                    title: 'UCP Protokolle',
                    description: 'Checkout-Sessions und Webhook-Zustellungen anzeigen',
                },
                navigation: {
                    sessions: 'Checkout-Sessions',
                    webhooks: 'Webhook-Zustellungen',
                },
                sessions: {
                    title: 'Checkout-Sessions',
                    description: 'Checkout-Session-Verlauf anzeigen und debuggen',
                    columnSession: 'Session-ID',
                    columnShop: 'Shop',
                    columnStatus: 'Status',
                    columnPlatform: 'Plattform',
                    columnOrder: 'Bestellung',
                    columnCreated: 'Erstellt',
                    columnExpires: 'Läuft ab',
                    filterStatus: 'Status',
                    filterAll: 'Alle',
                    statusIncomplete: 'Unvollständig',
                    statusComplete: 'Abgeschlossen',
                    statusFailed: 'Fehlgeschlagen',
                    statusExpired: 'Abgelaufen',
                    detailTitle: 'Session-Details',
                    detailGeneral: 'Allgemein',
                    detailCart: 'Warenkorb-Daten',
                    detailPayment: 'Zahlung',
                    detailAddresses: 'Adressen',
                    noData: 'Keine Checkout-Sessions gefunden',
                },
                webhooks: {
                    title: 'Webhook-Zustellungen',
                    description: 'Webhook-Zustellungsstatus überwachen',
                    columnEvent: 'Ereignis',
                    columnTarget: 'Ziel-URL',
                    columnStatus: 'Status',
                    columnAttempts: 'Versuche',
                    columnLastError: 'Letzter Fehler',
                    columnCreated: 'Erstellt',
                    columnDelivered: 'Zugestellt',
                    filterStatus: 'Status',
                    filterAll: 'Alle',
                    statusPending: 'Ausstehend',
                    statusSent: 'Gesendet',
                    statusFailed: 'Fehlgeschlagen',
                    statusRetrying: 'Wiederholung',
                    retryButton: 'Wiederholen',
                    retrySuccess: 'Webhook-Wiederholung initiiert',
                    retryFailed: 'Webhook-Wiederholung fehlgeschlagen',
                    noData: 'Keine Webhook-Zustellungen gefunden',
                },
            },
        },
        'nl-NL': {
            'ucp-logs': {
                general: {
                    title: 'UCP Logs',
                    description: 'Bekijk checkout sessies en webhook leveringen',
                },
                navigation: {
                    sessions: 'Checkout Sessies',
                    webhooks: 'Webhook Leveringen',
                },
                sessions: {
                    title: 'Checkout Sessies',
                    description: 'Bekijk en debug checkout sessie geschiedenis',
                    columnSession: 'Sessie ID',
                    columnShop: 'Winkel',
                    columnStatus: 'Status',
                    columnPlatform: 'Platform',
                    columnOrder: 'Bestelling',
                    columnCreated: 'Aangemaakt',
                    columnExpires: 'Verloopt',
                    filterStatus: 'Status',
                    filterAll: 'Alle',
                    statusIncomplete: 'Onvolledig',
                    statusComplete: 'Voltooid',
                    statusFailed: 'Mislukt',
                    statusExpired: 'Verlopen',
                    detailTitle: 'Sessie Details',
                    detailGeneral: 'Algemeen',
                    detailCart: 'Winkelwagen Data',
                    detailPayment: 'Betaling',
                    detailAddresses: 'Adressen',
                    noData: 'Geen checkout sessies gevonden',
                },
                webhooks: {
                    title: 'Webhook Leveringen',
                    description: 'Monitor webhook levering status',
                    columnEvent: 'Event',
                    columnTarget: 'Doel URL',
                    columnStatus: 'Status',
                    columnAttempts: 'Pogingen',
                    columnLastError: 'Laatste Fout',
                    columnCreated: 'Aangemaakt',
                    columnDelivered: 'Afgeleverd',
                    filterStatus: 'Status',
                    filterAll: 'Alle',
                    statusPending: 'In afwachting',
                    statusSent: 'Verzonden',
                    statusFailed: 'Mislukt',
                    statusRetrying: 'Opnieuw proberen',
                    retryButton: 'Opnieuw',
                    retrySuccess: 'Webhook opnieuw verzenden gestart',
                    retryFailed: 'Webhook opnieuw verzenden mislukt',
                    noData: 'Geen webhook leveringen gevonden',
                },
            },
        },
    },

    routes: {
        sessions: {
            component: 'ucp-logs-sessions',
            path: 'sessions',
            meta: {
                parentPath: 'sw.settings.index',
            },
        },
        webhooks: {
            component: 'ucp-logs-webhooks',
            path: 'webhooks',
            meta: {
                parentPath: 'sw.settings.index',
            },
        },
    },

    settingsItem: {
        group: 'plugins',
        to: 'ucp.logs.sessions',
        icon: 'regular-file-text',
        privilege: 'system.plugin_maintain',
    },

    navigation: [
        {
            id: 'ucp-logs',
            label: 'ucp-logs.general.title',
            color: '#ff6b35',
            icon: 'regular-file-text',
            parent: 'sw-settings',
            position: 110,
        },
        {
            id: 'ucp-logs-sessions',
            label: 'ucp-logs.navigation.sessions',
            path: 'ucp.logs.sessions',
            parent: 'ucp-logs',
            position: 1,
        },
        {
            id: 'ucp-logs-webhooks',
            label: 'ucp-logs.navigation.webhooks',
            path: 'ucp.logs.webhooks',
            parent: 'ucp-logs',
            position: 2,
        },
    ],
});
